import {
  OxButton, 
  OxButtonGroup, 
  OxIcon, 
  OxCollapse,
  OxCollapseItem,
  OxAlert,
  OxTooltip,
  OxPopconfirm,
  OxDropdown,
  OxDropdownItem,
  OxMessage,
  OxNotification,
  OxInput,
  OxMessageBox,
  OxLoading,
  OxSwitch,
  OxSelect,
  OxOption,
  OxForm,
  OxFormItem,
} from "../components";
import type { Plugin } from "vue";

//类型声明为 Vue 插件数组
export default [
  OxButton, 
  OxButtonGroup, 
  OxIcon, 
  OxCollapse,
  OxCollapseItem,
  OxAlert,
  OxTooltip,
  OxPopconfirm,
  OxDropdown,
  OxDropdownItem,
  OxMessage,
  OxNotification,
  OxInput,
  OxMessageBox,
  OxLoading,
  OxSwitch,
  OxSelect,
  OxOption,
  OxForm,
  OxFormItem,
] as Plugin[];